using System.Text;
using Flx.Compiler.Semantics;

namespace Flx.Compiler.Codegen.C;

internal sealed class CGenerator
{
    public string Generate(ModuleSymbol module, CompilationModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("/* Generated by flxc. Do not edit. */");
        builder.AppendLine($"/* Source: {module.SourceFile.DisplayPath} */");
        builder.AppendLine();

        foreach (var header in module.CImports.Select(import => import.Header).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal))
            builder.AppendLine($"#include <{header}>");

        if (module.CImports.Count > 0)
            builder.AppendLine();

        if (model.RequiresRuntime)
        {
            builder.AppendLine("#include \"flx_runtime.g.h\"");
            builder.AppendLine();
        }

        foreach (var function in module.Functions)
        {
            var rewrittenBody = new CBodyLowerer(function, module, model).Lower();
            rewrittenBody = AddBodyLineDirective(rewrittenBody, function);

            builder.AppendLine($"#line {function.Syntax.DeclarationLocation.Line} \"{EscapeLinePath(function.SourceFile.DisplayPath)}\"");
            builder.Append($"{CTypeNames.MapType(function.ReturnType, model)} {function.MangledName}(");
            builder.Append(CTypeNames.FormatFunctionParameters(function, model));
            builder.Append(") ");
            builder.AppendLine(rewrittenBody);
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static string AddBodyLineDirective(string body, FunctionSymbol function)
    {
        if (!body.StartsWith('{'))
            return body;

        var bodyLine = function.SourceFile.GetLocation(function.Syntax.BodyStart).Line + 1;
        var directive = $"#line {bodyLine} \"{EscapeLinePath(function.SourceFile.DisplayPath)}\"\n";

        if (body.Length == 1)
            return "{\n" + directive + "}";

        if (body.Length > 2 && body[1] == '\r' && body[2] == '\n')
            return "{\r\n" + directive + body[3..];

        if (body[1] == '\n')
            return "{\n" + directive + body[2..];

        return "{\n" + directive + body[1..];
    }

    internal static string EscapeLinePath(string path)
    {
        return path.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    }
}
