using System.Text;
using Flx.Compiler.Semantics;

namespace Flx.Compiler.Codegen.C;

internal sealed class CGenerator
{
    public string Generate(ModuleSymbol module, CompilationModel model, bool absoluteLineDirectives, string umbrellaHeaderFileName)
    {
        var builder = new StringBuilder();
        builder.AppendLine("/* Generated by flxc. Do not edit. */");
        builder.AppendLine($"/* Source: {module.SourceFile.DisplayPath} */");
        builder.AppendLine();
        builder.AppendLine($"#include \"{umbrellaHeaderFileName}\"");
        builder.AppendLine();

        if (model.RequiresScheduleBreakSupport)
        {
            builder.AppendLine("extern int flx_schedule_break_requested;");
            builder.AppendLine("static inline void flx_schedule_request_break(void) {");
            builder.AppendLine("    flx_schedule_break_requested = 1;");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        if (model.RequiresProgramArguments)
        {
            builder.AppendLine("extern i32 flx_argc;");
            builder.AppendLine("extern flx_array_string flx_argv;");
            builder.AppendLine();
        }

        foreach (var global in module.Globals)
            builder.AppendLine($"{CTypeNames.MapType(global.Type, model, module)} {global.Name}{FormatGlobalInitializer(global)};");

        if (module.Globals.Count > 0)
            builder.AppendLine();

        foreach (var function in module.Functions)
        {
            var rewrittenBody = new CBodyLowerer(function, module, model).Lower();
            rewrittenBody = AddBodyLineDirective(rewrittenBody, function, absoluteLineDirectives);

            builder.AppendLine($"#line {function.Syntax.DeclarationLocation.Line} \"{EscapeLinePath(LinePath(function.SourceFile, absoluteLineDirectives))}\"");
            builder.Append($"{CTypeNames.MapType(function.ReturnType, model, module)} {function.MangledName}(");
            builder.Append(CTypeNames.FormatFunctionParameters(function, model));
            builder.Append(") ");
            builder.AppendLine(rewrittenBody);
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static string FormatGlobalInitializer(GlobalVariableSymbol global)
    {
        if (global.Initializer is not { Length: > 0 } initializer)
            return "";

        var rewritten = CBodyRewriter.Rewrite(
            initializer,
            global.Module.CImportsByAlias,
            global.SourceFile,
            global.Syntax.DeclarationLocation.Position);
        return " = " + rewritten;
    }

    private static string AddBodyLineDirective(string body, FunctionSymbol function, bool absoluteLineDirectives)
    {
        if (!body.StartsWith('{'))
            return body;

        var bodyLine = function.SourceFile.GetLocation(function.Syntax.BodyStart).Line + 1;
        var directive = $"#line {bodyLine} \"{EscapeLinePath(LinePath(function.SourceFile, absoluteLineDirectives))}\"\n";

        if (body.Length == 1)
            return "{\n" + directive + "}";

        if (body.Length > 2 && body[1] == '\r' && body[2] == '\n')
            return "{\r\n" + directive + body[3..];

        if (body[1] == '\n')
            return "{\n" + directive + body[2..];

        return "{\n" + directive + body[1..];
    }

    internal static string EscapeLinePath(string path)
    {
        return path.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string LinePath(Flx.Compiler.Frontend.SourceFile sourceFile, bool absoluteLineDirectives)
    {
        return absoluteLineDirectives ? sourceFile.FullPath : sourceFile.DisplayPath;
    }
}
