using System.Text;
using Flx.Compiler.Semantics;

namespace Flx.Compiler.Codegen.C;

internal sealed class CHeaderGenerator
{
    public string Generate(ModuleSymbol module, CompilationModel model, string headerFileName, string runtimeHeaderIncludePath)
    {
        var builder = new StringBuilder();
        var guard = IncludeGuard(headerFileName);

        builder.AppendLine("/* Generated by flxc. Do not edit. */");
        builder.AppendLine($"/* Source: {module.SourceFile.DisplayPath} */");
        builder.AppendLine();
        builder.AppendLine($"#ifndef {guard}");
        builder.AppendLine($"#define {guard}");
        builder.AppendLine();

        var preservedDirectives = CollectPreservedPreprocessorDirectives(module.SourceFile.OriginalText);
        foreach (var directive in preservedDirectives)
            builder.AppendLine(directive);

        if (preservedDirectives.Count > 0)
            builder.AppendLine();

        if (model.RequiresRuntime)
        {
            builder.AppendLine($"#include \"{runtimeHeaderIncludePath}\"");
            builder.AppendLine();
        }
        else if (ModuleUsesSizeT(module))
        {
            builder.AppendLine("#include <stddef.h>");
            builder.AppendLine();
        }

        foreach (var header in module.CImports.Select(import => import.Header).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal))
            builder.AppendLine($"#include <{header}>");

        if (module.CImports.Count > 0)
            builder.AppendLine();

        foreach (var global in module.Globals)
            builder.AppendLine($"extern {CTypeNames.MapType(global.Type, model, module)} {global.Name};");

        if (module.Globals.Count > 0)
            builder.AppendLine();

        foreach (var function in module.Functions)
            builder.AppendLine(CTypeNames.FormatExternPrototype(function, model));

        if (module.Functions.Count > 0)
            builder.AppendLine();

        builder.AppendLine($"#endif /* {guard} */");
        return builder.ToString();
    }

    internal static bool ModuleUsesSizeT(ModuleSymbol module)
    {
        return module.Globals.Any(global => global.Type == "usize") ||
               module.Functions.Any(function =>
                   function.ReturnType == "usize" ||
                   function.Parameters.Any(parameter => parameter.Type == "usize"));
    }

    internal static IReadOnlyList<string> CollectPreservedPreprocessorDirectives(string text)
    {
        var directives = new List<string>();
        using var reader = new StringReader(text);
        while (reader.ReadLine() is { } line)
        {
            var trimmed = line.TrimStart();
            if (trimmed.StartsWith("#define ", StringComparison.Ordinal) ||
                trimmed.StartsWith("#undef ", StringComparison.Ordinal))
            {
                directives.Add(trimmed);
            }
        }

        return directives;
    }

    private static string IncludeGuard(string headerFileName)
    {
        return "FLX_" + CTypeNames.SafeIdentifier(headerFileName).ToUpperInvariant() + "_";
    }
}
