using System.Text;
using Flx.Compiler.Frontend;
using Flx.Compiler.Semantics;

namespace Flx.Compiler.Codegen.C;

internal sealed class CMainGenerator
{
    public string Generate(CompilationModel model)
    {
        var schedule = model.Schedule ?? throw new InvalidOperationException("Cannot generate main without exactly one schedule.");
        var calls = ResolveCalls(model, schedule).ToArray();
        var builder = new StringBuilder();

        builder.AppendLine("/* Generated by flxc. Do not edit. */");
        builder.AppendLine("/* Schedule main */");
        builder.AppendLine();

        if (model.RequiresRuntime)
        {
            builder.AppendLine("#include \"flx_runtime.g.h\"");
            builder.AppendLine();
        }

        foreach (var function in calls.DistinctBy(function => function.MangledName).OrderBy(function => function.MangledName, StringComparer.Ordinal))
            builder.AppendLine(CTypeNames.FormatExternPrototype(function, model));

        builder.AppendLine();

        if (model.RequiresScheduleBreakSupport)
        {
            builder.AppendLine("int flx_schedule_break_requested = 0;");
            builder.AppendLine();
        }

        builder.AppendLine("int main(int argc, char **argv) {");
        builder.AppendLine("    (void)argc;");
        builder.AppendLine("    (void)argv;");
        builder.AppendLine();

        if (model.RequiresRuntime)
        {
            builder.AppendLine("    flx_world world;");
            builder.AppendLine("    flx_world_init(&world);");
            builder.AppendLine();
        }

        foreach (var step in schedule.Steps)
            AppendScheduleStep(builder, step, model);

        if (model.RequiresRuntime)
        {
            builder.AppendLine();
            builder.AppendLine("    flx_world_destroy(&world);");
        }

        builder.AppendLine();
        builder.AppendLine("    return 0;");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static IEnumerable<FunctionSymbol> ResolveCalls(CompilationModel model, ScheduleDeclSyntax schedule)
    {
        foreach (var step in schedule.Steps.OfType<RunStepSyntax>())
        {
            foreach (var function in model.FunctionRegistry
                         .LookupSourceName(step.Name)
                .Where(function => function.Parameters.Count == 0 ||
                                   (function.Parameters.Count == 1 && model.PrefabsByName.ContainsKey(function.Parameters[0].Type)))
                         .OrderBy(function => function.SourceFile.DisplayPath, StringComparer.Ordinal)
                         .ThenBy(function => function.Location.Line)
                         .ThenBy(function => function.MangledName, StringComparer.Ordinal))
            {
                yield return function;
            }
        }
    }

    private static void AppendScheduleStep(StringBuilder builder, ScheduleStmtSyntax step, CompilationModel model)
    {
        switch (step)
        {
            case RunStepSyntax run:
                foreach (var function in ResolveRun(model, run))
                    AppendScheduleCall(builder, function, model);
                break;
            case LabelStepSyntax label:
                builder.AppendLine();
                builder.AppendLine($"{FormatLabel(label.Name)}:");
                break;
            case LoopToStepSyntax loopTo:
                builder.AppendLine();
                builder.AppendLine("    if (!flx_schedule_break_requested) {");
                builder.AppendLine($"        goto {FormatLabel(loopTo.TargetLabel)};");
                builder.AppendLine("    }");
                builder.AppendLine("    flx_schedule_break_requested = 0;");
                break;
        }
    }

    private static IEnumerable<FunctionSymbol> ResolveRun(CompilationModel model, RunStepSyntax step)
    {
        return model.FunctionRegistry
            .LookupSourceName(step.Name)
            .Where(function => function.Parameters.Count == 0 ||
                               (function.Parameters.Count == 1 && model.PrefabsByName.ContainsKey(function.Parameters[0].Type)))
            .OrderBy(function => function.SourceFile.DisplayPath, StringComparer.Ordinal)
            .ThenBy(function => function.Location.Line)
            .ThenBy(function => function.MangledName, StringComparer.Ordinal);
    }

    private static void AppendScheduleCall(StringBuilder builder, FunctionSymbol function, CompilationModel model)
    {
        if (function.Parameters.Count == 0)
        {
            var args = function.NeedsWorld ? "&world" : "";
            builder.AppendLine($"    {function.MangledName}({args});");
            return;
        }

        var prefabName = function.Parameters[0].Type;
        builder.AppendLine($"    for (usize i = 0; i < world.{CTypeNames.CountField(prefabName)}; ++i) {{");
        builder.AppendLine($"        {CTypeNames.ViewType(prefabName)} {function.Parameters[0].Name} = {CTypeNames.GetFunction(prefabName)}(&world, i);");
        builder.AppendLine($"        {function.MangledName}({function.Parameters[0].Name});");
        builder.AppendLine("    }");
    }

    private static string FormatLabel(string labelName) => "flx_schedule_label_" + CTypeNames.SafeIdentifier(labelName);
}
