using System.Text;
using Flx.Compiler.Frontend;
using Flx.Compiler.Semantics;

namespace Flx.Compiler.Codegen.C;

internal sealed class CMainGenerator
{
    public string Generate(CompilationModel model, string umbrellaHeaderFileName)
    {
        var schedule = model.Schedule ?? throw new InvalidOperationException("Cannot generate main without exactly one schedule.");
        var builder = new StringBuilder();

        builder.AppendLine("/* Generated by flxc. Do not edit. */");
        builder.AppendLine("/* Schedule main */");
        builder.AppendLine();
        builder.AppendLine($"#include \"{umbrellaHeaderFileName}\"");
        builder.AppendLine();

        if (model.RequiresScheduleBreakSupport)
        {
            builder.AppendLine("int flx_schedule_break_requested = 0;");
            builder.AppendLine();
        }

        if (model.RequiresProgramArguments)
        {
            builder.AppendLine("i32 flx_argc = 0;");
            builder.AppendLine("flx_array_string flx_argv;");
            builder.AppendLine();
        }

        AppendParallelHelpers(builder, schedule, model);

        builder.AppendLine("int main(int c_argc, char **c_argv) {");
        if (model.RequiresProgramArguments)
        {
            builder.AppendLine("    flx_argc = (i32)c_argc;");
            builder.AppendLine("    flx_array_string_init_from_c_argv(&flx_argv, c_argc, c_argv);");
        }
        else
        {
            builder.AppendLine("    (void)c_argc;");
            builder.AppendLine("    (void)c_argv;");
        }
        builder.AppendLine();

        if (model.RequiresRuntime)
        {
            builder.AppendLine("    flx_world world;");
            builder.AppendLine("    flx_world_init(&world);");
            builder.AppendLine();
        }

        foreach (var step in schedule.Steps)
            AppendScheduleStep(builder, step, model);

        if (model.RequiresRuntime)
        {
            builder.AppendLine();
            builder.AppendLine("    flx_world_destroy(&world);");
        }

        if (model.RequiresProgramArguments)
        {
            builder.AppendLine();
            builder.AppendLine("    flx_array_string_destroy_borrowed(&flx_argv);");
        }

        builder.AppendLine();
        builder.AppendLine("    return 0;");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void AppendScheduleStep(StringBuilder builder, ScheduleStmtSyntax step, CompilationModel model)
    {
        switch (step)
        {
            case RunStepSyntax run:
                foreach (var function in ResolveRun(model, run))
                    AppendScheduleCall(builder, function, model);
                break;
            case LabelStepSyntax label:
                builder.AppendLine();
                builder.AppendLine($"{FormatLabel(label.Name)}:");
                break;
            case LoopToStepSyntax loopTo:
                builder.AppendLine();
                builder.AppendLine("    if (!flx_schedule_break_requested) {");
                builder.AppendLine($"        goto {FormatLabel(loopTo.TargetLabel)};");
                builder.AppendLine("    }");
                builder.AppendLine("    flx_schedule_break_requested = 0;");
                break;
        }
    }

    private static IEnumerable<FunctionSymbol> ResolveRun(CompilationModel model, RunStepSyntax step)
    {
        var resolution = ScheduleTargetResolver.Resolve(model, step, model.ScheduleModule);
        var functions = resolution.Functions
            .Where(function => function.Parameters.Count == 0 ||
                               (function.Parameters.Count == 1 && model.PrefabsByFullName.ContainsKey(function.Parameters[0].Type)));

        return resolution.IsWildcard
            ? functions
                .OrderBy(function => function.FullName, StringComparer.Ordinal)
                .ThenBy(function => function.MangledName, StringComparer.Ordinal)
            : functions
                .OrderBy(function => function.SourceFile.DisplayPath, StringComparer.Ordinal)
                .ThenBy(function => function.Location.Line)
                .ThenBy(function => function.MangledName, StringComparer.Ordinal);
    }

    private static void AppendScheduleCall(StringBuilder builder, FunctionSymbol function, CompilationModel model)
    {
        if (function.Parameters.Count == 0)
        {
            var args = function.NeedsWorld ? "&world" : "";
            builder.AppendLine($"    {function.MangledName}({args});");
            return;
        }

        if (CanRunScheduleStepParallel(function, model))
        {
            var helperName = ParallelHelperName(function);
            builder.AppendLine($"    {helperName}_ctx {helperName}_data = {{ &world }};");
            builder.AppendLine($"    flx_parallel_for(world.{CTypeNames.CountField(function.Parameters[0].Type)}, 1, {helperName}_range, &{helperName}_data);");
            return;
        }

        var prefabName = function.Parameters[0].Type;
        builder.AppendLine($"    for (usize i = 0; i < world.{CTypeNames.CountField(prefabName)}; ++i) {{");
        builder.AppendLine($"        {CTypeNames.ViewType(prefabName)} {function.Parameters[0].Name} = {CTypeNames.GetFunction(prefabName)}(&world, i);");
        builder.AppendLine($"        {function.MangledName}({function.Parameters[0].Name});");
        builder.AppendLine("    }");
    }

    private static void AppendParallelHelpers(StringBuilder builder, ScheduleDeclSyntax schedule, CompilationModel model)
    {
        var helpers = schedule.Steps
            .OfType<RunStepSyntax>()
            .SelectMany(step => ResolveRun(model, step))
            .Where(function => CanRunScheduleStepParallel(function, model))
            .DistinctBy(function => function.MangledName)
            .OrderBy(function => function.FullName, StringComparer.Ordinal)
            .ThenBy(function => function.MangledName, StringComparer.Ordinal)
            .ToArray();

        foreach (var function in helpers)
        {
            var helperName = ParallelHelperName(function);
            var prefabName = function.Parameters[0].Type;
            var parameterName = function.Parameters[0].Name;

            builder.AppendLine($"typedef struct {helperName}_ctx {{");
            builder.AppendLine("    flx_world *world;");
            builder.AppendLine($"}} {helperName}_ctx;");
            builder.AppendLine();
            builder.AppendLine($"static void {helperName}_range(void *user, usize begin, usize end) {{");
            builder.AppendLine($"    {helperName}_ctx *ctx = ({helperName}_ctx *)user;");
            builder.AppendLine("    for (usize i = begin; i < end; ++i) {");
            builder.AppendLine($"        {CTypeNames.ViewType(prefabName)} {parameterName} = {CTypeNames.GetFunction(prefabName)}(ctx->world, i);");
            builder.AppendLine($"        {function.MangledName}({parameterName});");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }
    }

    private static bool CanRunScheduleStepParallel(FunctionSymbol function, CompilationModel model)
    {
        return function.Parameters.Count == 1 &&
               model.PrefabsByFullName.ContainsKey(function.Parameters[0].Type) &&
               function.ParallelInfo.CanRunParallel;
    }

    private static string ParallelHelperName(FunctionSymbol function)
    {
        return "flx_parallel_" + CTypeNames.SafeIdentifier(function.MangledName);
    }

    private static string FormatLabel(string labelName) => "flx_schedule_label_" + CTypeNames.SafeIdentifier(labelName);
}
