using System.Text;
using Flx.Compiler.Semantics;

namespace Flx.Compiler.Codegen.C;

internal sealed class CUmbrellaHeaderGenerator
{
    public string Generate(CompilationModel model, IReadOnlyList<ModuleHeader> moduleHeaders)
    {
        var builder = new StringBuilder();

        builder.AppendLine("/* Generated by flxc. Do not edit. */");
        builder.AppendLine("/* Program declarations */");
        builder.AppendLine();
        builder.AppendLine("#ifndef FLX_PROGRAM_G_H");
        builder.AppendLine("#define FLX_PROGRAM_G_H");
        builder.AppendLine();

        if (model.RequiresRuntime)
        {
            builder.AppendLine("#include \"flx_runtime.g.h\"");
            builder.AppendLine();
        }

        foreach (var header in model.ExternalHeaders.Order(StringComparer.OrdinalIgnoreCase))
            builder.AppendLine($"#include \"{header.Replace("\\", "/", StringComparison.Ordinal)}\"");

        if (model.ExternalHeaders.Count > 0)
            builder.AppendLine();

        foreach (var header in moduleHeaders.Select(header => header.HeaderFileName).Order(StringComparer.OrdinalIgnoreCase))
            builder.AppendLine($"#include \"{header.Replace("\\", "/", StringComparison.Ordinal)}\"");

        builder.AppendLine();
        builder.AppendLine("#endif /* FLX_PROGRAM_G_H */");
        return builder.ToString();
    }
}

internal sealed record ModuleHeader(ModuleSymbol Module, string HeaderFileName);
